### ISSUE TITLE
Net_maxfilesize limit (16 MB) - CSGO Server/debian

### ISSUE THREAD

**Issue by suzuka12345** [GameServerManagers/Game-Server-Configs#1]
Hey I will like to change that so I can have bigger custom maps I have add it to csgo-server.cfg

IT is like this in the file
//download
sv_minrate 0
sv_maxrate 0
fps_max 1000
sm_cvar sv_hibernate_when_empty 0
Cl_allowdownload 1
cl_allowupload 1
net_maxfilesize 75
 
but it does not seem to change its still tells me 16 MB limit issue
also cant seem to make map vote to work can you help?

**Comment by cedarlug** [comment]
A lot of things here.

First, this isn't really related to this repo, as this repo holds standard configurations for common gameservers.  It isn't intended to be a repository of the most tweaked and specialized versions for specific deployments.  That would be impossible to manage, yes?

Second, from my (limited) understanding, net_maxfilesize is limited to 64, so - again in my limited understanding - you are attempting to make it larger than the max, so it defaults back to 16.

Third, with such a large map, you should be using sv_download instead of pushing it through the server.  (But again, not relevant to this repository.)
